// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOp_dPbWbSQyWaqcoHQAzruVbAQn0GC0A',
    appId: '1:203119332761:web:b0f1c3b5317e512f189708',
    messagingSenderId: '203119332761',
    projectId: 'duck-auction',
    authDomain: 'duck-auction.firebaseapp.com',
    storageBucket: 'duck-auction.firebasestorage.app',
    measurementId: 'G-7K5KP3XC4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpxz6zpW63DEJCsLuHHwEPs0LOAah1CAM',
    appId: '1:203119332761:android:3909b89d69a16400189708',
    messagingSenderId: '203119332761',
    projectId: 'duck-auction',
    storageBucket: 'duck-auction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb6NROD2pWft_go2krvD-wp9A8AAit1xw',
    appId: '1:203119332761:ios:5ac9fae19e58831f189708',
    messagingSenderId: '203119332761',
    projectId: 'duck-auction',
    storageBucket: 'duck-auction.firebasestorage.app',
    iosClientId: '203119332761-1nn45mu4ds3ji6i28iu1gudh41hbrc1m.apps.googleusercontent.com',
    iosBundleId: 'com.duckauction.app',
  );
}
